server:
  port: 8083

  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:h2:file:./data/administracion
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
